### ISSUE TITLE
Support different endpoint mappings over a configuration file

### ISSUE THREAD

**Issue by marceloboeira** [14-bits/crowd#3]
It would be essential to have a external configuration file that we could use to setup the route/sink adapters maps:

```yaml
routes:
  - path: "/foo"
    sink: 
      adapter: redis
      uri: "redis://[USER]:[PASSWORD]@[IP]:[PORT]"
  - path: "/bar"
    sink: 
      adapter: sqs
      ...
```
