### ISSUE TITLE
Sink Buffer

### ISSUE THREAD

**Issue by marceloboeira** [14-bits/crowd#4]
Add support to a sink buffer, to avoid round-trips on every incoming request. 

The buffer should be configurable through the configuration file: #3.

The buffer should have a configurable timeout too, something like, "100 messages OR 1 second" and it could be adjustable per sink.

```yaml
routes:
  - path: "/foo"
    sink: 
      adapter: redis
      uri: "redis://[USER]:[PASSWORD]@[IP]:[PORT]"
      buffer:
        size: 100
        timeout: 1s
```

**document** that sink buffers are **volatile** and shouldn't be used for situations that there is no tolerance for message dropping.
